### ISSUE TITLE
Link to wiki?

### ISSUE THREAD

**Issue by nhtranngoc** [googlecreativelab/anypixel#11]
After taking a look at the documentation, I have found that some of the links that lead to the wiki is not available (eg. https://github.com/googlecreativelab/anypixel/wiki/Communications-Packets leads back to the main project page) - Is there a hidden wiki somewhere, or is it simply not published yet?

**Comment by ryburke** [comment]
We haven't set up the wiki yet. All of the documentation is handled at the README level. Where did you surface that link that you shared? I'll look into it.
Thanks!

**Comment by jonahsmith** [comment]
If it helps, I encountered that link in the readme for `/backend/chromebridge` (at the end of [this section](https://github.com/googlecreativelab/anypixel/tree/master/backend/chromebridge#pixel-data)).

**Comment by ryburke** [comment]
Ah @jonahsmith thank you! We didn't catch that. That link is in error. All documentation is done at the README level. There should not be a wiki.
