### ISSUE TITLE
Previewer

### ISSUE THREAD

**Issue by artyprog** [googlecreativelab/anypixel#2]
Thanks for this great library.
Where can we download the previewer ?

Regards

**Comment by Bre77** [comment]
https://github.com/googlecreativelab/anypixel/tree/master/frontend/previewer

**Comment by jeremyabel** [comment]
thanks @Bre77!

**Comment by artyprog** [comment]
Than you Brett

2016-06-03 11:31 GMT+02:00 Brett notifications@github.com:
