### ISSUE TITLE
Approximate Cost

### ISSUE THREAD

**Issue by forbze** [googlecreativelab/anypixel#21]
Hey,

We're looking at building one of these as an internal project for our office - but I'd love to know the approximate cost to build?

If you have any ballpark figures - It'd be great to know.

Steve

**Comment by ajiblock** [comment]
Hey Steve,

The costs will vary drastically depending on many factors from size to materials to the engineering standards that you need to follow (structural, electrical, local codes, etc). We would recommend partnering with a local experiential/fabrication production company to accurately bid out the costs.
