### ISSUE TITLE
Simple diet-project to get started

### ISSUE THREAD

**Issue by tshamz** [googlecreativelab/anypixel#23]
If I'm having confusion and pretty high level questions like:

- what's a PWM module?
- as the physical size of the project grows, which parts am I gonna need to keep buying more of?
- widget X can do ABC, but widget Y can do ABC _and_ XYZ... I wonder if I should buy widget Y?

are these, or questions like them, just the beginning and it's only gonna get worse moving forward? My guess is that a lot of web developers will see this and say to themselves, "cool. definitely want to build that." But that thought will then quickly be followed by another of, "shit. what's a PCB? is this going to cost me a small fortune? will I need to buy tools for this? i hope i don't electrocute myself..."

I think the idea mentioned at the end of [this comment](https://github.com/googlecreativelab/anypixel/issues/1#issuecomment-224397613) might be something that would be helpful at providing people with no hardware experience a context to learn in and enough basic knowledge that they could tool around with that and then afterwards have enough confidence to go off and figure out the rest on their own.

**Comment by ryburke** [comment]
The version that we open sourced is a commercial build for the Google lobby. As a web developer, these hardware questions are totally fair. And you're right, you will likely have more as you work through the project. 

We are currently developing a simplified version running off a Raspberry Pi. We have a lot of other projects right now, but we hope to have this complete in the next month or two.

**Comment by tshamz** [comment]
Awesome, thanks for the response. I'll be tracking closely and waiting patiently for the simplified version. 🙌🏻

**Comment by ryburke** [comment]
@tshamz We'll be posting an example tomorrow morning with AnyPixel running off a Raspberry Pi controlling a single button.
