### ISSUE TITLE
Emulator Not Working 

### ISSUE THREAD

**Issue by kennyor** [googlecreativelab/anypixel#25]
While those backend application installed, any reasons that only ChromeBridge working fine but Emulator without showing the blue box on the top left corner?
Anyone got an idea?

**Comment by ajiblock** [comment]
Thanks for posting this. The emulator seems to be working for us. Can you describe your issue in more detail and we can see if we can help.

**Comment by kennyor** [comment]
Basically, I am starting to try the instruction of project at the point: "Starter Example: AnyPixel with Raspberry Pi", since I have only limited hardware material on hands, I am wondering how far I could complete this creative project.

Hardware:
I am using Raspberry Pi 2Model B without Neopixel, therefore I made a console log to simulate the led response if button press or the signal from chromebridge.

Running the app from host computer:
After putting "getting-started-rpi"to right place and run build, the chrome extension "emulator" was also installed and launched. Here the emulator shows all units are in black. After I launch ChromeBridge, I got exact result as the screen capture provided on "rpi-example/chromebridge", but emulator still black.

So my question is, in which stage I should be able to trigger the units turning blue from black?

Thanks for your time to answer me!

**Comment by nick-jonas** [comment]
Hi @kennyor!

I just set it up again from scratch and I was able to recreate it so I think I know where you're reaching a snag.  You are probably getting an error in your ChromeBridge from the app running if you open up your inspector.  First, you need to make sure you followed these instructions in the README:

Install Sample App Copy and paste frontend/examples/getting-started-rpi into appserver/public/apps/ and then:
```
cd appserver/public/apps/getting-started-rpi
npm install
npm run build
```

And then, (and this was a mistake on our part and now is fixed), you actually need to do one extra step when setting up your app server, which is to manually create a ```public/js``` folder.  So I would kill the app server process (```forever stop <pid>```) and follow these steps again:

### Install & Run App Server
```
cd /backend/appserver 
mkdir -p public/js
npm install
npm install anypixel
npm start
```

After you do that, and you have the udp-manager and appserver running in the background (and refreshed), you should see the blinking blue square in your emulator.  Let me know if that works!

**Comment by kennyor** [comment]
Hi @nick-jonas!

I really appreciate this opportunity to get help from you! Everything working well after create the folder, learn a lot;)
